branches:
  except:
  - /^stage.*$/
sudo: required
services: 
- docker
env:
  global:
    - DOCKER_CLIENT_TIMEOUT: 120
    - COMPOSE_HTTP_TIMEOUT: 120
    - MATLAB_UID: 2000
    - MATLAB_GID: 2000
slim: &slim
  stage: Slim9.9
  os: linux
  language: shell
  script:
    - license=MATLAB_LICENSE_${MATLAB_VERSION}
    - export MATLAB_LICENSE=$(eval echo "\$$license")
    - if [ "distribution/mexa64/mym.mexa64" -nt "distribution/mexmaci64/mym.mexmaci64" ]; then exit 1; fi
    - if [ "distribution/mexa64/mym.mexa64" -nt "distribution/mexw64/mym.mexw64" ]; then exit 1; fi
    - docker-compose -f LNX-docker-compose.yml up --exit-code-from app
jobs:
  include:
    - <<: *slim
      env:
      - MATLAB_VERSION: R2019a
      - MYSQL_TAG: 8.0
    - <<: *slim
      env:
      - MATLAB_VERSION: R2019a
      - MYSQL_TAG: 5.7
    - <<: *slim
      env:
      - MATLAB_VERSION: R2019a
      - MYSQL_TAG: 5.6
    - <<: *slim
      env:
      - MATLAB_VERSION: R2018b
      - MYSQL_TAG: 5.7
    - <<: *slim
      env:
      - MATLAB_VERSION: R2016b
      - MYSQL_TAG: 5.7